/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'blog-posts': BlogPost;
    authors: Author;
    media: Media;
    'petition-signatures': PetitionSignature;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    users: User;
    'analytics-ga4-snapshots': AnalyticsGa4Snapshot;
    'analytics-gsc-snapshots': AnalyticsGscSnapshot;
    'analytics-keyword-rankings': AnalyticsKeywordRanking;
    'analytics-competitor-snapshots': AnalyticsCompetitorSnapshot;
    'tracked-keywords': TrackedKeyword;
    'tracked-competitors': TrackedCompetitor;
    'llm-target-prompts': LlmTargetPrompt;
    'llm-mention-snapshots': LlmMentionSnapshot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'petition-signatures': PetitionSignaturesSelect<false> | PetitionSignaturesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'analytics-ga4-snapshots': AnalyticsGa4SnapshotsSelect<false> | AnalyticsGa4SnapshotsSelect<true>;
    'analytics-gsc-snapshots': AnalyticsGscSnapshotsSelect<false> | AnalyticsGscSnapshotsSelect<true>;
    'analytics-keyword-rankings': AnalyticsKeywordRankingsSelect<false> | AnalyticsKeywordRankingsSelect<true>;
    'analytics-competitor-snapshots': AnalyticsCompetitorSnapshotsSelect<false> | AnalyticsCompetitorSnapshotsSelect<true>;
    'tracked-keywords': TrackedKeywordsSelect<false> | TrackedKeywordsSelect<true>;
    'tracked-competitors': TrackedCompetitorsSelect<false> | TrackedCompetitorsSelect<true>;
    'llm-target-prompts': LlmTargetPromptsSelect<false> | LlmTargetPromptsSelect<true>;
    'llm-mention-snapshots': LlmMentionSnapshotsSelect<false> | LlmMentionSnapshotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Newsletters, events, building showcases, tours, demolition alerts — all site content managed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Primary keyword, 2-5 words. For most posts, no dates (e.g. "austin-modern-homes"). For recurring events, append the year so each year stays unique (e.g. "annual-gala-2026").
   */
  slug: string;
  /**
   * Auto-generated by Claude. Short summary shown in listings and previews (1–2 sentences). You can edit after generation.
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Determines where the post appears: Newsletter → /newsletter · Advocacy → /mid-texas-modern/demolition-schedules · Event → /events · Tour → /tours.
   */
  category?:
    | ('newsletter' | 'news' | 'building-spotlight' | 'advocacy' | 'events' | 'self-guided-tours' | 'digital-tours')
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pick from the Authors list. Manage authors under Content → Authors.
   */
  byline?: (number | null) | Author;
  /**
   * Legacy inline author info — kept for backwards compatibility. Use the "Author" dropdown above instead.
   */
  author?: {
    name?: string | null;
    role?: string | null;
    /**
     * URL of author photo (optional)
     */
    image?: string | null;
  };
  /**
   * Auto-set when first published. Override if needed.
   */
  publishedDate?: string | null;
  status: 'draft' | 'published';
  /**
   * Thumbnail used in listings and social share previews.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Large hero banner shown full-width at the top of newsletter articles. Recommended 2400×1200 or wider.
   */
  bannerImage?: (number | null) | Media;
  /**
   * Up to 10 images shown in the editorial grid below the article title (newsletter layout only).
   */
  galleryImages?:
    | {
        image: number | Media;
        /**
         * Short caption shown beneath the image (optional).
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-calculated from body on save. Override if needed.
   */
  readingTime?: number | null;
  seo?: {
    /**
     * Defaults to title if empty. Aim for 50–60 chars.
     */
    metaTitle?: string | null;
    /**
     * Defaults to excerpt if empty. Aim for 140–160 chars.
     */
    metaDescription?: string | null;
  };
  relatedPosts?:
    | {
        postSlug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only used on Building Spotlight posts — populates the detail card and project team on the building showcase page.
   */
  buildingShowcase?: {
    architect?: string | null;
    /**
     * e.g. "1962" or "1958–1962"
     */
    yearBuilt?: string | null;
    /**
     * e.g. "Mid-Century Modern", "Ranch", "International Style"
     */
    style?: string | null;
    address?: string | null;
    /**
     * e.g. "Austin, TX"
     */
    city?: string | null;
    status?: ('standing' | 'at-risk' | 'demolished' | 'renovated' | 'landmarked') | null;
    /**
     * Short sentence shown beside the building details card.
     */
    tagline?: string | null;
    /**
     * Architect, engineers, landscape, interior design, etc. Each entry gets a row in the Project Team section.
     */
    projectTeam?:
      | {
          /**
           * e.g. "Architect", "Landscape Design", "Structural Engineer"
           */
          role: string;
          name: string;
          /**
           * Optional URL to link the name (e.g. their website).
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Only used on Event posts — populates the details panel on the event page.
   */
  eventDetails?: {
    /**
     * Display date, e.g. "Saturday, May 10, 2026" or "May 10–12, 2026"
     */
    eventDate?: string | null;
    /**
     * e.g. "10:00 AM – 2:00 PM CT"
     */
    eventTime?: string | null;
    /**
     * e.g. "Austin Central Library, 710 W César Chávez St"
     */
    venue?: string | null;
    /**
     * e.g. "Austin, TX"
     */
    city?: string | null;
    /**
     * e.g. "Free", "$15 members / $25 general", "Donation-based"
     */
    price?: string | null;
    /**
     * External registration or ticket link (optional).
     */
    registrationUrl?: string | null;
    /**
     * Button text for the registration link.
     */
    registrationLabel?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Contributors and authors. Each gets a public profile page at /author/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL slug, e.g. "jane-doe". Used at /author/<slug>.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * e.g. "Editor", "Staff Writer", "Volunteer Contributor"
   */
  role?: string | null;
  /**
   * Optional affiliation, e.g. company or firm.
   */
  company?: string | null;
  /**
   * Short label shown above the name (e.g. "STAFF WRITER", "CONTRIBUTOR", "GUEST AUTHOR").
   */
  tagline?: string | null;
  /**
   * Headshot used on the author profile page (square crop works best).
   */
  photo?: (number | null) | Media;
  /**
   * Author biography. Shown in the "About" section of the profile page.
   */
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What this author is most passionate about. Optional — useful for nonprofits or cause-driven sites.
   */
  advocacy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tags shown on the profile (e.g. "Editorial", "Research", "Photography").
   */
  expertise?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    /**
     * Used for the "Email Author" button on the profile page.
     */
    email?: string | null;
    /**
     * Twitter/X handle without the @.
     */
    twitter?: string | null;
    /**
     * Instagram handle without the @.
     */
    instagram?: string | null;
    /**
     * Full LinkedIn profile URL.
     */
    linkedin?: string | null;
    /**
     * Personal or company website URL.
     */
    website?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "petition-signatures".
 */
export interface PetitionSignature {
  id: number;
  /**
   * Slug of the demolition alert post this signature applies to.
   */
  postSlug: string;
  firstName: string;
  lastName: string;
  email: string;
  city?: string | null;
  /**
   * Optional public comment (only shown if displayPublic is true).
   */
  comment?: string | null;
  /**
   * If checked, the signer name (first name + last initial) and comment may appear on the public page.
   */
  displayPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the public contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Mark when you've replied to or otherwise actioned this message.
   */
  handled?: boolean | null;
  /**
   * Private notes for the team — not sent to the contact.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Emails captured from the public newsletter signup form. Each new newsletter published in Website Content (category Newsletter) is automatically emailed to everyone here who has not unsubscribed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Where on the site this person signed up (e.g. "footer", "homepage-hero"). Optional, set by the form.
   */
  source?: string | null;
  /**
   * True once the subscriber has verified their email. V1 ships single opt-in (defaults to true on create) — flip to false to require confirmation in future.
   */
  confirmed?: boolean | null;
  /**
   * True if the subscriber clicked the unsubscribe link in any newsletter. Broadcast logic skips anyone where this is true.
   */
  unsubscribed?: boolean | null;
  /**
   * Timestamp the subscriber unsubscribed.
   */
  unsubscribedAt?: string | null;
  /**
   * One-click unsubscribe token used in newsletter footers. Auto-generated on create — do not edit.
   */
  unsubscribeToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Auto-populated daily by the analytics cron. Read by /admin/analytics/overview. Manual edits not recommended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-ga4-snapshots".
 */
export interface AnalyticsGa4Snapshot {
  id: number;
  snapshotDate: string;
  sessions?: number | null;
  /**
   * Active users for the day.
   */
  users?: number | null;
  newUsers?: number | null;
  pageviews?: number | null;
  /**
   * Decimal 0-1.
   */
  bounceRate?: number | null;
  /**
   * Seconds.
   */
  avgSessionDuration?: number | null;
  conversions?: number | null;
  /**
   * Top 10 pages by pageviews. Array of { path, pageviews }.
   */
  topPages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Top 10 traffic sources by sessions. Array of { source, sessions }.
   */
  topSources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-populated daily by the analytics cron. Read by /admin/analytics/overview. Manual edits not recommended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-gsc-snapshots".
 */
export interface AnalyticsGscSnapshot {
  id: number;
  snapshotDate: string;
  impressions?: number | null;
  clicks?: number | null;
  /**
   * Decimal 0-1.
   */
  ctr?: number | null;
  /**
   * Average ranking position across queries.
   */
  avgPosition?: number | null;
  /**
   * Top 25 queries. Array of { query, impressions, clicks, ctr, position }.
   */
  topQueries?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Top 25 pages. Array of { page, impressions, clicks, ctr, position }.
   */
  topPages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-populated weekly by the DataForSEO cron. Read by /admin/analytics/overview. Manual edits not recommended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-keyword-rankings".
 */
export interface AnalyticsKeywordRanking {
  id: number;
  snapshotDate: string;
  keyword: string;
  location?: string | null;
  /**
   * Google position (1-100). Null if not in top 100.
   */
  position?: number | null;
  /**
   * The page on your site that ranked.
   */
  url?: string | null;
  /**
   * Average monthly search volume for the keyword.
   */
  searchVolume?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-populated weekly by the DataForSEO cron. Read by /admin/analytics/overview. Manual edits not recommended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-competitor-snapshots".
 */
export interface AnalyticsCompetitorSnapshot {
  id: number;
  snapshotDate: string;
  domain: string;
  /**
   * DataForSEO estimated monthly organic traffic.
   */
  estimatedTraffic?: number | null;
  /**
   * Total keywords ranked in top 100.
   */
  rankedKeywordsCount?: number | null;
  /**
   * Keywords both this competitor and your site rank for.
   */
  overlapWithUs?: number | null;
  /**
   * Top 25 keywords by search volume. Array of { keyword, position, searchVolume, url }.
   */
  topKeywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Top 25 keywords this competitor ranks for that you do not. Array of { keyword, theirPosition, searchVolume, theirUrl }.
   */
  gapKeywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Keywords you want to monitor in Search Console and weekly keyword rankings. Add one per row. Inactive keywords stay in history but are skipped on next cron run.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-keywords".
 */
export interface TrackedKeyword {
  id: number;
  keyword: string;
  /**
   * City + region for geo-targeted ranking checks (DataForSEO uses this). Format: "City, State, Country" for local; "Country" for national.
   */
  location?: string | null;
  searchEngine?: 'google' | null;
  /**
   * Uncheck to stop tracking without losing history.
   */
  active?: boolean | null;
  /**
   * Optional context for why this keyword matters.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Competitor domains to compare against your site weekly. Add up to ~5 to keep DataForSEO costs in check. Bare domain only (no https://, no www).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-competitors".
 */
export interface TrackedCompetitor {
  id: number;
  /**
   * Bare domain only — e.g. "competitor.com" (no protocol, no path).
   */
  domain: string;
  /**
   * Friendly name for the dashboard, e.g. "Competitor Inc.".
   */
  label?: string | null;
  /**
   * Uncheck to stop tracking without losing history.
   */
  active?: boolean | null;
  /**
   * Optional context for why this competitor matters.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions a real user might type into ChatGPT/Claude/Perplexity that should mention your brand. Tested weekly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-target-prompts".
 */
export interface LlmTargetPrompt {
  id: number;
  /**
   * The full question or prompt to send to each LLM.
   */
  prompt: string;
  /**
   * Optional context for why this prompt matters.
   */
  description?: string | null;
  /**
   * Uncheck to stop testing without losing history.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-populated weekly. Read by /admin/analytics/overview. Manual edits not recommended.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-mention-snapshots".
 */
export interface LlmMentionSnapshot {
  id: number;
  snapshotDate: string;
  /**
   * The prompt text at snapshot time (denormalized).
   */
  prompt: string;
  platform: 'claude' | 'chatgpt' | 'perplexity';
  /**
   * True if any sample mentioned the brand.
   */
  mentioned?: boolean | null;
  /**
   * Number of independent prompt runs against this platform for this row.
   */
  samplesTotal?: number | null;
  /**
   * How many of the samples cited the brand.
   */
  samplesMentioned?: number | null;
  /**
   * True if the response specifically cited your domain as a URL/source.
   */
  domainCited?: boolean | null;
  /**
   * Array of { domain, mentioned: bool } for each tracked competitor.
   */
  competitorMentions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Excerpt of the response near the relevant mention, or first 400 chars if no mention.
   */
  responseSnippet?: string | null;
  /**
   * Full LLM response for retrospective analysis (prose only — citation URLs are stored in citedUrls).
   */
  responseFull?: string | null;
  /**
   * Array of source URLs the model cited (Perplexity returns these explicitly; Claude/ChatGPT typically empty).
   */
  citedUrls?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set if the LLM call failed for this row.
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'petition-signatures';
        value: number | PetitionSignature;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'analytics-ga4-snapshots';
        value: number | AnalyticsGa4Snapshot;
      } | null)
    | ({
        relationTo: 'analytics-gsc-snapshots';
        value: number | AnalyticsGscSnapshot;
      } | null)
    | ({
        relationTo: 'analytics-keyword-rankings';
        value: number | AnalyticsKeywordRanking;
      } | null)
    | ({
        relationTo: 'analytics-competitor-snapshots';
        value: number | AnalyticsCompetitorSnapshot;
      } | null)
    | ({
        relationTo: 'tracked-keywords';
        value: number | TrackedKeyword;
      } | null)
    | ({
        relationTo: 'tracked-competitors';
        value: number | TrackedCompetitor;
      } | null)
    | ({
        relationTo: 'llm-target-prompts';
        value: number | LlmTargetPrompt;
      } | null)
    | ({
        relationTo: 'llm-mention-snapshots';
        value: number | LlmMentionSnapshot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  byline?: T;
  author?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
      };
  publishedDate?: T;
  status?: T;
  featuredImage?: T;
  bannerImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  readingTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  relatedPosts?:
    | T
    | {
        postSlug?: T;
        id?: T;
      };
  buildingShowcase?:
    | T
    | {
        architect?: T;
        yearBuilt?: T;
        style?: T;
        address?: T;
        city?: T;
        status?: T;
        tagline?: T;
        projectTeam?:
          | T
          | {
              role?: T;
              name?: T;
              link?: T;
              id?: T;
            };
      };
  eventDetails?:
    | T
    | {
        eventDate?: T;
        eventTime?: T;
        venue?: T;
        city?: T;
        price?: T;
        registrationUrl?: T;
        registrationLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  role?: T;
  company?: T;
  tagline?: T;
  photo?: T;
  about?: T;
  advocacy?: T;
  expertise?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  social?:
    | T
    | {
        email?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
        website?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "petition-signatures_select".
 */
export interface PetitionSignaturesSelect<T extends boolean = true> {
  postSlug?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  city?: T;
  comment?: T;
  displayPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  handled?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  confirmed?: T;
  unsubscribed?: T;
  unsubscribedAt?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-ga4-snapshots_select".
 */
export interface AnalyticsGa4SnapshotsSelect<T extends boolean = true> {
  snapshotDate?: T;
  sessions?: T;
  users?: T;
  newUsers?: T;
  pageviews?: T;
  bounceRate?: T;
  avgSessionDuration?: T;
  conversions?: T;
  topPages?: T;
  topSources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-gsc-snapshots_select".
 */
export interface AnalyticsGscSnapshotsSelect<T extends boolean = true> {
  snapshotDate?: T;
  impressions?: T;
  clicks?: T;
  ctr?: T;
  avgPosition?: T;
  topQueries?: T;
  topPages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-keyword-rankings_select".
 */
export interface AnalyticsKeywordRankingsSelect<T extends boolean = true> {
  snapshotDate?: T;
  keyword?: T;
  location?: T;
  position?: T;
  url?: T;
  searchVolume?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-competitor-snapshots_select".
 */
export interface AnalyticsCompetitorSnapshotsSelect<T extends boolean = true> {
  snapshotDate?: T;
  domain?: T;
  estimatedTraffic?: T;
  rankedKeywordsCount?: T;
  overlapWithUs?: T;
  topKeywords?: T;
  gapKeywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-keywords_select".
 */
export interface TrackedKeywordsSelect<T extends boolean = true> {
  keyword?: T;
  location?: T;
  searchEngine?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-competitors_select".
 */
export interface TrackedCompetitorsSelect<T extends boolean = true> {
  domain?: T;
  label?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-target-prompts_select".
 */
export interface LlmTargetPromptsSelect<T extends boolean = true> {
  prompt?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-mention-snapshots_select".
 */
export interface LlmMentionSnapshotsSelect<T extends boolean = true> {
  snapshotDate?: T;
  prompt?: T;
  platform?: T;
  mentioned?: T;
  samplesTotal?: T;
  samplesMentioned?: T;
  domainCited?: T;
  competitorMentions?: T;
  responseSnippet?: T;
  responseFull?: T;
  citedUrls?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Control how Claude drafts blog posts. Edit the system prompt to shape voice, structure, and output quality.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * Your Anthropic API key (starts with sk-ant-). Get one at console.anthropic.com. This key is used for all AI content generation and stored securely in the database.
   */
  anthropicApiKey?: string | null;
  /**
   * Base instructions Claude follows for every post (voice, style, words to avoid, SEO/GEO rules, JSON output spec). Preset-specific structure rules are appended on top of this for each post type.
   */
  systemPrompt: string;
  /**
   * Which Claude model to use. Sonnet is a good default. Opus for the highest-quality writing (~5x cost). Haiku for quick drafts (~1/5 cost).
   */
  model: 'claude-sonnet-4-5' | 'claude-opus-4-6' | 'claude-haiku-4-5';
  /**
   * Maximum length of generated content (~4 chars per token). 4096 = roughly 1000 words total including JSON overhead. Increase for longer posts.
   */
  maxTokens: number;
  /**
   * Creativity dial: 0 = deterministic and repetitive, 1 = creative and varied. 0.7 is a good default for editorial content.
   */
  temperature?: number | null;
  /**
   * Presets that appear in the "Generate with Claude" dropdown. Each preset adds its own structure rules on top of the base system prompt above.
   */
  postTypes?:
    | {
        /**
         * Internal identifier, lowercase, no spaces (e.g. "building-showcase").
         */
        slug: string;
        /**
         * Display name in the dropdown.
         */
        label: string;
        /**
         * Category to set automatically when this preset is chosen.
         */
        defaultCategory?:
          | (
              | 'newsletter'
              | 'news'
              | 'building-spotlight'
              | 'advocacy'
              | 'events'
              | 'self-guided-tours'
              | 'digital-tours'
            )
          | null;
        /**
         * Extra instructions appended to the base system prompt. Be specific about structure, tone, and content for this post type.
         */
        additionalInstructions: string;
        /**
         * When enabled, the AI will search the web for current facts about the topic via Perplexity and cite sources at the end of the post. Recommended for newsletters, demolition alerts, news, and advocacy posts. Not recommended for evergreen content like tours.
         */
        useLiveResearch?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  anthropicApiKey?: T;
  systemPrompt?: T;
  model?: T;
  maxTokens?: T;
  temperature?: T;
  postTypes?:
    | T
    | {
        slug?: T;
        label?: T;
        defaultCategory?: T;
        additionalInstructions?: T;
        useLiveResearch?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}