import type { CollectionConfig } from 'payload'
import { airportSectionsField, locationSectionsField } from './blogPostSectionFields'

/**
 * BlogPosts collection — articles, newsletters, case studies, etc.
 * Rendered on the public site at /blog and /blog/[slug] via SSR.
 */
export const BlogPosts: CollectionConfig = {
  slug: 'blog-posts',
  labels: {
    singular: 'Website Content',
    plural: 'Website Content',
  },
  access: {
    // Public read — required for the Astro site to fetch via API
    read: () => true,
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'category', 'status', 'publishedDate'],
    group: 'Content',
    description: 'Newsletters, events, building showcases, tours, demolition alerts — all site content managed here.',
  },
  hooks: {
    beforeChange: [
      ({ data, originalDoc }) => {
        if (!data?.readingTime && data?.body) {
          const text = JSON.stringify(data.body)
          const textMatches = text.match(/"text":"([^"]*)"/g) || []
          const wordCount = textMatches
            .join(' ')
            .replace(/"text":"/g, '')
            .replace(/"/g, '')
            .split(/\s+/)
            .filter((w) => w.length > 0).length
          data.readingTime = Math.max(1, Math.round(wordCount / 200))
        }
        if (data?.status === 'published' && (!originalDoc || originalDoc.status !== 'published')) {
          if (!data.publishedDate) {
            data.publishedDate = new Date().toISOString()
          }
        }
        return data
      },
    ],
    afterChange: [
      async ({ doc, previousDoc, req, operation }) => {
        // Only fire when a Newsletter post crosses the line into "published"
        // for the first time. Editing an already-published newsletter must
        // not re-blast subscribers.
        const becamePublished =
          doc?.status === 'published' &&
          (operation === 'create' ? true : previousDoc?.status !== 'published')
        if (!becamePublished) return doc
        if (doc?.category !== 'newsletter') return doc

        try {
          const { broadcastNewsletter } = await import('@/lib/newsletter-broadcast')
          const result = await broadcastNewsletter(req.payload, {
            id: doc.id,
            title: doc.title,
            slug: doc.slug,
            excerpt: doc.excerpt,
            heroImage: doc.heroImage,
            publishedDate: doc.publishedDate,
          })
          req.payload.logger.info(
            { broadcastResult: result, postId: doc.id, title: doc.title },
            '[newsletter-broadcast] sent',
          )
        } catch (err: any) {
          // Never let a broadcast failure roll back the publish. The post
          // is already saved; we just log and move on.
          req.payload.logger.error(
            { err: err?.message ?? String(err), postId: doc.id },
            '[newsletter-broadcast] failed',
          )
        }
        return doc
      },
    ],
  },
  fields: [
    {
      name: 'autoSave',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/AutoSaveField#default',
        },
      },
    },
    {
      name: 'aiGenerator',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/GenerateAIButton#default',
        },
      },
    },
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        position: 'sidebar',
        description: 'Primary keyword, 2-5 words. For most posts, no dates (e.g. "austin-modern-homes"). For recurring events, append the year so each year stays unique (e.g. "annual-gala-2026").',
      },
    },
    {
      name: 'excerpt',
      type: 'textarea',
      admin: {
        description: 'Auto-generated by Claude. Short summary shown in listings and previews (1–2 sentences). You can edit after generation.',
      },
    },
    {
      name: 'body',
      type: 'richText',
      admin: {
        description:
          'Long-form body for blog and news posts. Location and airport pages use the structured section fields below instead — leave this empty for those categories.',
      },
    },
    {
      name: 'category',
      type: 'select',
      options: [
        { label: 'Location Page (City)', value: 'location-page' },
        { label: 'Airport / FBO Page', value: 'airport-page' },
        { label: 'Blog Post', value: 'blog' },
        { label: 'News', value: 'news' },
      ],
      defaultValue: 'blog',
      admin: {
        description:
          'Determines where the post appears: Location Page → /private-jet-transfer/[slug] · Airport Page → /airports/[slug] · Blog → /blog/[slug] · News → /news/[slug].',
      },
    },
    {
      name: 'tags',
      type: 'array',
      fields: [
        {
          name: 'tag',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      name: 'byline',
      label: 'Author',
      type: 'relationship',
      relationTo: 'authors',
      admin: {
        description: 'Pick from the Authors list. Manage authors under Content → Authors.',
      },
    },
    {
      name: 'author',
      type: 'group',
      admin: {
        description: 'Legacy inline author info — kept for backwards compatibility. Use the "Author" dropdown above instead.',
        hidden: true,
      },
      fields: [
        {
          name: 'name',
          type: 'text',
          defaultValue: 'Staff',
        },
        {
          name: 'role',
          type: 'text',
        },
        {
          name: 'image',
          type: 'text',
          admin: {
            description: 'URL of author photo (optional)',
          },
        },
      ],
    },
    {
      name: 'publishedDate',
      type: 'date',
      admin: {
        position: 'sidebar',
        description: 'Auto-set when first published. Override if needed.',
        date: {
          pickerAppearance: 'dayOnly',
          displayFormat: 'yyyy-MM-dd',
        },
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' },
      ],
      admin: {
        position: 'sidebar',
        isSortable: false,
        components: {
          Field: '@/components/PublishButton#default',
        },
      },
    },
    {
      name: 'imageGenerator',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/GenerateImageButton#default',
        },
      },
    },
    {
      name: 'featuredImage',
      type: 'upload',
      relationTo: 'media',
      admin: {
        description: 'Thumbnail used in listings and social share previews.',
      },
    },
    {
      name: 'bannerImage',
      type: 'upload',
      relationTo: 'media',
      admin: {
        description:
          'Large hero banner shown full-width at the top of newsletter articles. Recommended 2400×1200 or wider.',
      },
    },
    {
      name: 'galleryImages',
      type: 'array',
      maxRows: 10,
      labels: { singular: 'Gallery Image', plural: 'Gallery Images' },
      admin: {
        description:
          'Up to 10 images shown in the editorial grid below the article title (newsletter layout only).',
      },
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: true,
        },
        {
          name: 'caption',
          type: 'text',
          admin: {
            description: 'Short caption shown beneath the image (optional).',
          },
        },
      ],
    },
    {
      name: 'readingTime',
      type: 'number',
      min: 1,
      admin: {
        position: 'sidebar',
        description: 'Auto-calculated from body on save. Override if needed.',
      },
    },
    {
      name: 'seo',
      type: 'group',
      fields: [
        {
          name: 'metaTitle',
          type: 'text',
          admin: {
            description: 'Defaults to title if empty. Aim for 50–60 chars.',
          },
        },
        {
          name: 'metaDescription',
          type: 'textarea',
          admin: {
            description: 'Defaults to excerpt if empty. Aim for 140–160 chars.',
          },
        },
      ],
    },
    {
      name: 'relatedPosts',
      type: 'array',
      fields: [
        {
          name: 'postSlug',
          type: 'text',
          required: true,
        },
      ],
    },
    locationSectionsField,
    airportSectionsField,
    {
      name: 'buildingShowcase',
      type: 'group',
      label: 'Building Showcase Details',
      admin: {
        description:
          'Only used on Building Spotlight posts — populates the detail card and project team on the building showcase page.',
        condition: (data) => data?.category === 'building-spotlight',
      },
      fields: [
        { name: 'architect', type: 'text' },
        { name: 'yearBuilt', type: 'text', admin: { description: 'e.g. "1962" or "1958–1962"' } },
        { name: 'style', type: 'text', admin: { description: 'e.g. "Mid-Century Modern", "Ranch", "International Style"' } },
        { name: 'address', type: 'text' },
        { name: 'city', type: 'text', admin: { description: 'e.g. "Austin, TX"' } },
        {
          name: 'status',
          type: 'select',
          options: [
            { label: 'Standing', value: 'standing' },
            { label: 'At Risk', value: 'at-risk' },
            { label: 'Demolished', value: 'demolished' },
            { label: 'Renovated', value: 'renovated' },
            { label: 'Landmarked', value: 'landmarked' },
          ],
        },
        {
          name: 'tagline',
          type: 'textarea',
          admin: { description: 'Short sentence shown beside the building details card.', rows: 2 },
        },
        {
          name: 'projectTeam',
          type: 'array',
          labels: { singular: 'Team Role', plural: 'Project Team' },
          admin: {
            description: 'Architect, engineers, landscape, interior design, etc. Each entry gets a row in the Project Team section.',
          },
          fields: [
            { name: 'role', type: 'text', required: true, admin: { description: 'e.g. "Architect", "Landscape Design", "Structural Engineer"' } },
            { name: 'name', type: 'text', required: true },
            { name: 'link', type: 'text', admin: { description: 'Optional URL to link the name (e.g. their website).' } },
          ],
        },
      ],
    },
    {
      name: 'eventDetails',
      type: 'group',
      label: 'Event Details',
      admin: {
        description: 'Only used on Event posts — populates the details panel on the event page.',
        condition: (data) => data?.category === 'events',
      },
      fields: [
        { name: 'eventDate', type: 'text', admin: { description: 'Display date, e.g. "Saturday, May 10, 2026" or "May 10–12, 2026"' } },
        { name: 'eventTime', type: 'text', admin: { description: 'e.g. "10:00 AM – 2:00 PM CT"' } },
        { name: 'venue', type: 'text', admin: { description: 'e.g. "Austin Central Library, 710 W César Chávez St"' } },
        { name: 'city', type: 'text', admin: { description: 'e.g. "Austin, TX"' } },
        { name: 'price', type: 'text', defaultValue: 'Free', admin: { description: 'e.g. "Free", "$15 members / $25 general", "Donation-based"' } },
        { name: 'registrationUrl', type: 'text', admin: { description: 'External registration or ticket link (optional).' } },
        { name: 'registrationLabel', type: 'text', defaultValue: 'Register Now', admin: { description: 'Button text for the registration link.' } },
      ],
    },
  ],
}
