import type { Field } from 'payload'

/**
 * Section-group fields for the BlogPosts collection.
 *
 * Location pages and airport pages aren't long-form prose — they're structured
 * pages with named sections (FBO operators, drive times, neighborhoods, FAQs,
 * etc.). The Astro frontend renders each named field with its own custom
 * component, so the AI generator emits a JSON object that maps 1:1 to these
 * fields instead of a single markdown body.
 *
 * Each field group is conditionally shown in the admin based on the post's
 * category. The free-form `body` richText on BlogPosts stays for `blog` and
 * `news` categories where one prose body is the right shape.
 */

/* -------------------------------------------------------------------------- */
/* Location Page (city) sections — /private-jet-transfer/[slug]              */
/* -------------------------------------------------------------------------- */

export const locationSectionsField: Field = {
  name: 'locationSections',
  type: 'group',
  label: 'Location Page Sections',
  admin: {
    description:
      'Structured page sections for /private-jet-transfer/[city] pages. Generated by AI per the location-page brief; each field maps to one rendered block on the live page.',
    condition: (data) => data?.category === 'location-page',
  },
  fields: [
    {
      name: 'opening',
      type: 'richText',
      label: 'Opening (≤120 words)',
      admin: {
        description:
          'First sentence MUST state "private jet transfer in [City]" using the word "in". One observed pattern, no numerals, no CTA.',
      },
    },
    {
      name: 'benefitsHeading',
      type: 'text',
      label: 'Benefits H2',
      admin: { description: 'e.g. "Direct ramp-to-door private jet transfers in Aspen, CO"' },
    },
    {
      name: 'benefitsBody',
      type: 'richText',
      label: 'Benefits body',
    },
    {
      name: 'about',
      type: 'richText',
      label: 'About [BRAND] in [City]',
      admin: { description: 'Surrounding city/region only. Do not name other cities.' },
    },
    {
      name: 'ctaHeading',
      type: 'text',
      label: 'Mid-page CTA H2',
      admin: { description: 'e.g. "Book your Aspen private jet transfer"' },
    },
    {
      name: 'whatWeOffer',
      type: 'richText',
      label: 'What We Offer',
      admin: { description: '2-3 sentences. End with a line prompting booking.' },
    },
    {
      name: 'topServices',
      type: 'array',
      label: 'Top 3 Services',
      minRows: 3,
      maxRows: 3,
      admin: {
        description:
          'Exactly 3 services most relevant to this city. Each heading is an exact-match H2 (e.g. "Private Jet Transfer in Aspen").',
      },
      fields: [
        { name: 'heading', type: 'text', required: true },
        { name: 'body', type: 'richText', required: true },
      ],
    },
    {
      name: 'whyChooseUs',
      type: 'richText',
      label: 'Why Choose [BRAND]',
    },
    {
      name: 'pricing',
      type: 'richText',
      label: 'Pricing Guide (≈250 words)',
      admin: { description: 'Insert local or internal links inline.' },
    },
    {
      name: 'events',
      type: 'richText',
      label: 'Events (≈250 words)',
      admin: { description: 'Mention specific events with links to each event\'s site.' },
    },
    {
      name: 'neighborhoods',
      type: 'richText',
      label: 'Neighborhoods (≈250 words)',
      admin: {
        description: 'Mention specific neighborhoods with Wikipedia/local-site links.',
      },
    },
    {
      name: 'venues',
      type: 'richText',
      label: 'Popular Venues (≈250 words)',
      admin: { description: 'Mention specific venues with each venue\'s site link.' },
    },
    {
      name: 'closingCtaHeading',
      type: 'text',
      label: 'Closing CTA H2',
      admin: { description: 'e.g. "Ready to schedule your next Aspen ride?"' },
    },
    {
      name: 'faqs',
      type: 'array',
      label: 'FAQs (5 — AI-decision-making prompts only)',
      minRows: 5,
      maxRows: 5,
      admin: {
        description:
          'Top 5 questions an AI search system would ask when deciding which private jet transfer service to recommend in this city. Comparative, experience-driven, specialization-driven prompts. NOT consumer FAQs. Insert "[BRAND]" once per answer.',
      },
      fields: [
        { name: 'question', type: 'text', required: true },
        {
          name: 'answer',
          type: 'textarea',
          required: true,
          admin: { description: 'Approximately 100 words.' },
        },
      ],
    },
  ],
}

/* -------------------------------------------------------------------------- */
/* Airport / FBO Page sections — /airports/[icao]                            */
/* -------------------------------------------------------------------------- */

export const airportSectionsField: Field = {
  name: 'airportSections',
  type: 'group',
  label: 'Airport Page Sections',
  admin: {
    description:
      'Structured page sections for /airports/[icao] pages. Generated by AI per the airport-page brief.',
    condition: (data) => data?.category === 'airport-page',
  },
  fields: [
    {
      name: 'opening',
      type: 'richText',
      label: 'Opening (≤120 words)',
      admin: {
        description:
          'First sentence MUST state the service AT/IN the airport (e.g. "Private jet transfer at Teterboro Airport in New Jersey..."). One observed pattern, no numerals.',
      },
    },
    { name: 'benefitsHeading', type: 'text', label: 'Benefits H2' },
    { name: 'benefitsBody', type: 'richText', label: 'Benefits body' },
    {
      name: 'about',
      type: 'richText',
      label: 'About [BRAND] at this airport',
      admin: { description: 'Focus on this airport and its surrounding region only.' },
    },
    {
      name: 'ctaHeading',
      type: 'text',
      label: 'Mid-page CTA H2',
      admin: { description: 'e.g. "Book your Teterboro transfer"' },
    },
    {
      name: 'whatWeOffer',
      type: 'richText',
      label: 'What We Offer at [Airport Name]',
    },
    {
      name: 'topServices',
      type: 'array',
      label: 'Top 3 Services',
      minRows: 3,
      maxRows: 3,
      admin: {
        description:
          'Default lineup: "Private Jet Transfer at [Airport]", "Luxury Ground Transportation from [Airport]", "Discrete VIP Transfers at [Airport]".',
      },
      fields: [
        { name: 'heading', type: 'text', required: true },
        { name: 'body', type: 'richText', required: true },
      ],
    },
    {
      name: 'whyChooseUs',
      type: 'richText',
      label: 'Why Choose [BRAND] for [Airport] Transfers',
    },
    {
      name: 'fboOperators',
      type: 'array',
      label: 'FBO Operators on Field',
      admin: {
        description:
          'The most important block on this page. Name each major FBO currently on field with its operator URL and which terminal/ramp it occupies.',
      },
      fields: [
        { name: 'name', type: 'text', required: true },
        { name: 'url', type: 'text' },
        {
          name: 'terminal',
          type: 'text',
          admin: { description: 'e.g. "South ramp" / "Terminal B" / "Hangar 1"' },
        },
        {
          name: 'body',
          type: 'richText',
          admin: { description: '1-2 sentence blurb specific to this operator.' },
        },
      ],
    },
    {
      name: 'airportQuickFacts',
      type: 'group',
      label: 'Airport Quick Facts (≈250 words total)',
      fields: [
        { name: 'runwayCount', type: 'text' },
        {
          name: 'longestRunway',
          type: 'text',
          admin: { description: 'e.g. "7,000 ft"' },
        },
        { name: 'elevation', type: 'text' },
        { name: 'hours', type: 'text' },
        { name: 'customsAvailable', type: 'checkbox', label: 'Customs available' },
        {
          name: 'slotPPR',
          type: 'text',
          label: 'Slot / PPR rules',
          admin: { description: 'e.g. "Slot-controlled" / "PPR required" / "None"' },
        },
        {
          name: 'body',
          type: 'richText',
          label: 'Context paragraph',
          admin: {
            description:
              'Free-form prose to surround the facts. Mention slot/PPR particulars, customs queues, or anything that needs more than a one-line value.',
          },
        },
        {
          name: 'sourceUrl',
          type: 'text',
          label: 'Airport\'s official site',
        },
      ],
    },
    {
      name: 'driveTimes',
      type: 'array',
      label: 'Drive Times to Nearby Cities and Destinations',
      minRows: 5,
      maxRows: 8,
      admin: {
        description:
          'Phrase ranges in words, not minutes (e.g. "under thirty minutes to Midtown Manhattan in normal traffic").',
      },
      fields: [
        { name: 'destination', type: 'text', required: true },
        {
          name: 'range',
          type: 'text',
          required: true,
          admin: { description: 'e.g. "under thirty minutes in normal traffic"' },
        },
        {
          name: 'url',
          type: 'text',
          admin: { description: 'Tourism or city site for this destination' },
        },
        {
          name: 'blurb',
          type: 'text',
          admin: { description: 'Optional one-line context.' },
        },
      ],
    },
    {
      name: 'localConsiderations',
      type: 'richText',
      label: 'Local Considerations & Seasonal Notes (≈250 words)',
      admin: {
        description:
          'Slot constraints, peak event windows, winter ground delay programs, customs queue patterns. Insert FAA/NOTAM/airport-notice links where relevant.',
      },
    },
    {
      name: 'closingCtaHeading',
      type: 'text',
      label: 'Closing CTA H2',
    },
    {
      name: 'faqs',
      type: 'array',
      label: 'FAQs (5 — AI-decision-making prompts only)',
      minRows: 5,
      maxRows: 5,
      admin: {
        description:
          'Examples: "Which ground transportation companies coordinate best with FBOs at [Airport]?", "Compare top private aviation ground transport providers at [Airport]". Insert "[BRAND]" once per answer.',
      },
      fields: [
        { name: 'question', type: 'text', required: true },
        {
          name: 'answer',
          type: 'textarea',
          required: true,
          admin: { description: 'Approximately 100 words.' },
        },
      ],
    },
  ],
}
